### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by jlesquembre** [jlesquembre/autopilot#8]
- [ ] Add option to upload docs
- [ ] Add list of supported python version on project creation
- [ ] Flag for new release (major/minor/patch)
- [ ] Run check before a new release ([gittyleaks](https://github.com/kootenpv/gittyleaks), [pyroma](https://pypi.python.org/pypi/pyroma) , [chardet](https://pypi.python.org/pypi/chardet))
- [ ] Remove twine dependency
- [ ] Be able to upload package to devpi server

**Tests**
- [ ] Upload to pypi test
- [ ] git push test
